### DISCUSSION TITLE
[Need Help] Getting started laravel for Windows users?

### DISCUSSION THREAD

**Discussion by sukrokucing** [php/frankenphp#1041] [General]
Hi, is there any best practice for windows users like me?

First of all, I have searched with the keyword "ERR_SSL_PROTOCOL_ERROR" but got nothing, this makes me more confident to start a new discussion here 😀

Here are my baby steps to try out FrankenPHP on my local machine:
1. Turn on my computer (Windows 11)
2. Open WSL2 (Ubuntu 22.04.4 LTS)
3. mkdir docker-laravel
4. cd docker-laravel
5. mkdir apps
6. create Dockerfile
```Dockerfile
FROM dunglas/frankenphp:latest-php8.3.7-bookworm

# install git, unzip
RUN apt-get update && apt-get install -y git unzip

ENV PHPEXT="opcache sockets gd zip bcmath pdo pdo_pgsql sodium exif pcntl intl"

RUN install-php-extensions ${PHPEXT}

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /apps

# ENTRYPOINT ["php", "artisan", "octane:frankenphp"]
```
7. create docker-compose.yml
```YAML
services:
  frankenphp8.3.7:
    container_name: my-apps
    build:
      context: .  # Use the current directory
    environment:
      - SERVERNAME=https://localhost:8100
    volumes:
      - ./apps/:/apps/
    # entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1 --port=8100 --admin-port=2019
    ports:
      - 8100:8100
      - 443:443
      - 80:80
      - 2019:2019
```
8. create install.sh
```sh
#!/bin/sh
docker compose build frankenphp8.3.7
docker compose run --rm frankenphp8.3.7 composer create-project laravel/laravel .
docker compose run --rm frankenphp8.3.7 composer require laravel/octane
docker compose run --rm frankenphp8.3.7 php artisan octane:install --server=frankenphp
docker compose run --rm frankenphp8.3.7 composer require laravel/telescope --dev
docker compose run --rm frankenphp8.3.7 php artisan telescope:install
docker compose run --rm frankenphp8.3.7 php artisan migrate

# write and remove comment # ENTRYPOINT ["php", "artisan", "octane:frankenphp"] in Dockerfile
sed -i 's/# ENTRYPOINT \["php", "artisan", "octane:frankenphp"\]/ENTRYPOINT \["php", "artisan", "octane:frankenphp"\]/' Dockerfile

# write and remove comment # entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1 --port=8100 --admin-port=2019 in docker-compose.yml
sed -i 's/# entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1 --port=8100 --admin-port=2019/entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1 --port=8100 --admin-port=2019/' docker-compose.yml
docker compose build frankenphp8.3.7
docker compose up frankenphp8.3.7
```
9. run ``` sh install.sh ```
10. accessing my browser (windows)
11. that's great success with laravel homepage

But, when i add ``` --https ``` on docker-compose.yml like this:
```YAML
services:
  frankenphp8.3.7:
    container_name: my-apps
    build:
      context: .  # Use the current directory
    environment:
      - SERVERNAME=https://localhost:8100
    volumes:
      - ./apps/:/apps/
    entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1 --port=8100 --admin-port=2019 --https
    ports:
      - 8100:8100
      - 443:443
      - 80:80
      - 2019:2019
```
then docker compose up again,

I just see "ERR_SSL_PROTOCOL_ERROR" in my browser (windows).

is there anything I did wrong?

Thanks in advance
