### DISCUSSION TITLE
Is it possible to build frankenphp docker on Alma Linux?

### DISCUSSION THREAD

**Discussion by geoidesic** [php/frankenphp#1109] [Q&A] [answered]
The provided docker image for frankenphp is based on Debian. I don't want to run Debian, I want to run Alma Linux, because that's what I've standardised around. 

Is it possible to provide an alternate Dockerfile to enable this?

E.g. This is how I was running it with PHP-fpm and Caddy:

```yml
networks:
  web-network:
services:
  caddy:
    image: caddy:latest
    restart: on-failure
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/logs:/logs
      - ./app:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web-network
    # this bit allows caddy on docker to see the listener on the external (to docker) port 8080 (which listens locally on my laptop)
    extra_hosts:
      host.docker.internal: host-gateway
  php:
    build: ./php
    tty: true
    restart: on-failure
    volumes:
      - ./app:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./php/conf.d/requests.ini:/usr/local/etc/php/conf.d/requests.ini
    networks:
      - web-network
    extra_hosts:
      host.docker.internal: host-gateway
    expose:
      - "9003"  # Expose the Xdebug port
  ```
  
  The idea being that the `build: ./php` builds an image from a Dockerfile that starts from `almalinux:9 AS base`.
  
  Have I got the wrong end of the stick?

**Comment by withinboredom** [comment]
We base the images off of the standard PHP images. You are welcome to build them off of another base image but `install-php-extensions` might not work and you'll have to install them the 'olde fashioned way.

**Reply by geoidesic** [reply]
I tried but I get this:
```
fatal error: Zend/zend_types.h: No such file or directory
```

Here's the docker compose yml:
```yml
networks:
  web-network:
services:
  php:
    build: ./php
    platform: linux/amd64
    tty: true
    restart: on-failure
    volumes:
      - ./app:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./php/conf.d/requests.ini:/usr/local/etc/php/conf.d/requests.ini
    networks:
      - web-network
    extra_hosts:
      host.docker.internal: host-gateway
    expose:
      - "9003"  # Expose the Xdebug port

  mysql:
    image: mysql/mysql-server:latest-aarch64
    restart: on-failure
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aasportch10700
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_SQL_MODE: "NO_ENGINE_SUBSTITUTION"

    volumes:
      - $PWD/db/data:/var/lib/mysql
      - $PWD/db/config:/etc/mysql/conf.d
    networks:
      - web-network
    extra_hosts:
      host.docker.internal: host-gateway

  phpmyadmin:
    image: phpmyadmin
    tty: true
    working_dir: $PWD/phpmyadmin
    ports:
        - "8888:80"
    networks:
        - web-network
    environment:
        PMA_HOST: "mysql"
        PMA_PORT: "3306"
        PMA_USER: "root"
        PMA_PASSWORD: "root"

  frankenphp:
    build:
      context: .
      dockerfile: php/caddy/frankenphp/Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - ./app:/app
    # Add any other necessary configurations here

```

Here's the Dockerfile

```Dockerfile
# Start with AlmaLinux 9 base
FROM --platform=linux/amd64 almalinux:9 AS base

WORKDIR /app


# Enable PHP 8.2 repo (or other version if needed)
RUN dnf update -y

RUN dnf install -y dnf-plugins-core
RUN dnf config-manager --set-enabled crb


RUN dnf install -y \
    epel-release \
    dnf-utils \
    && dnf clean all

RUN dnf install -y https://rpms.remirepo.net/enterprise/remi-release-9.rpm && \
    dnf module enable php:remi-8.2 -y 


RUN dnf groupinstall -y "Development Tools"
RUN dnf install -y gcc gcc-c++
RUN echo "GCC version:" && gcc --version

    
RUN dnf install -y \
    git \
    make \
    autoconf \
    mailcap \
    libcap \
    zlib-devel \
    libargon2-devel \
    brotli-devel \
    libcurl-devel \
    oniguruma-devel \
    readline-devel \
    libsodium-devel \
    sqlite-devel \
    openssl-devel \
    php-devel \
    && dnf clean all


# Install PHP and required extensions
RUN dnf install -y \
    php \
    php-intl \
    php-pdo \
    php-mysqli \
    php-gd \
    php-zip \
    && dnf clean all

# Clone FrankenPHP repository
RUN git clone https://github.com/dunglas/frankenphp.git /app/frankenphp

# Set up Go environment
RUN curl -LO https://go.dev/dl/go1.21.1.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.21.1.linux-amd64.tar.gz && \
    rm go1.21.1.linux-amd64.tar.gz

ENV PATH="/usr/local/go/bin:$PATH"

# Switch to FrankenPHP directory and build
WORKDIR /app/frankenphp

# Install Go modules and build FrankenPHP
RUN go mod tidy && \
    GOBIN=/usr/local/bin go install -tags 'brotli watcher' -ldflags "-w -s" ./...

# Set capabilities to allow binding to low-numbered ports
RUN setcap cap_net_bind_service=+ep /usr/local/bin/frankenphp

# Copy necessary files for FrankenPHP
COPY php/caddy/frankenphp/Caddyfile /etc/caddy/Caddyfile

# Expose necessary ports
EXPOSE 80 443 443/udp 2019

CMD ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]

HEALTHCHECK CMD curl -f http://localhost:2019/metrics || exit 1
```


Any ideas?

**Reply by withinboredom** [reply]
You are missing the php sources.

```dockerfile
RUN dnf install -y \
    php \
    php-intl \
    php-pdo \
    php-mysqli \
    php-gd \
    php-zip \
    && dnf clean all
```

You need the ZTS (thread-safe) version of php, the NTS (non-thread-safe) version will NOT work with FrankenPHP

**Reply by withinboredom** [reply]
Oh, and PHP has to be compiled with `--disable-zend-signals --enable-zend-max-execution-timers` or certain PHP features may not work correctly. You should be able to see the `./configure` command php-info.

**Reply by geoidesic** [reply]
Where would I find all the necessary `./configure` options listed?

**Reply by geoidesic** [reply]
I've spent a whole day on this. It's beyond my abilities. I give up.
Real pity as I'd like my local env to match my production environment.

**Reply by dunglas** [reply]
@geoidesic follow these instructions, they should work on any UNIX, including Alma: https://frankenphp.dev/docs/compile/

**Reply by geoidesic** [reply]
Nope. I tried that. No luck. I just go around in circles. Maybe it's because I'm running docker on Mac silicon? I'm not sure but it sure doesn't work. Here's the Dockerfile I tried with:

```Dockerfile
# Base image for AlmaLinux 9 on AArch64
FROM almalinux:9 AS common
# Install EPEL and CBR repositories
RUN dnf -y update && \
    dnf clean all

RUN dnf install -y epel-release \
    && dnf config-manager --set-enabled crb \
    && dnf clean all

# Install dependencies
RUN dnf -y update && \
    dnf install -y \
    gcc \
    gcc-c++ \
    make \
    brotli-devel \
    tar \
    libticonv \
    bison \
    re2c \
    pkgconfig \
    openssl-devel \
    libxml2-devel \
    sqlite-devel \
    oniguruma-devel \
    libpng-devel \
    libjpeg-devel \
    libzip-devel \
    inotify-tools \
    git 
    
# Download and install Go manually
RUN curl -LO https://go.dev/dl/go1.22.0.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.22.0.linux-amd64.tar.gz && \
    rm go1.22.0.linux-amd64.tar.gz

# Add Go to PATH
ENV PATH="/usr/local/go/bin:${PATH}"


# Download and extract PHP source
WORKDIR /usr/src/php
RUN curl -L https://www.php.net/distributions/php-8.2.11.tar.gz | tar xz --strip-components=1

# Configure PHP for FrankenPHP build
RUN ./configure \
    --enable-embed \
    --enable-zts \
    --disable-zend-signals \
    --enable-zend-max-execution-timers && \
    make -j"$(nproc)" && \
    make install

# Set environment variables for cross-compiling on ARM64
ENV GOARCH=arm64 \
    CGO_ENABLED=1

# Download and compile FrankenPHP with adjusted flags for ARM64
WORKDIR /usr/src
RUN curl -L https://github.com/dunglas/frankenphp/archive/refs/heads/main.tar.gz | tar xz && \
    cd frankenphp-main/caddy/frankenphp && \
    CGO_CFLAGS="$(php-config --includes)" \
    CGO_LDFLAGS="$(php-config --ldflags | sed 's/-m64//') $(php-config --libs)" \
    go build -tags=nobadger,nomysql,nopgx

# Final stage to copy the binary to a clean image
FROM almalinux:9

# Copy compiled PHP and FrankenPHP binary from builder stage
COPY --from=common /usr/local/bin/php /usr/local/bin/php
COPY --from=common /usr/src/frankenphp-main/caddy/frankenphp/frankenphp /usr/local/bin/frankenphp

# Default command
CMD ["/usr/local/bin/frankenphp"]
```

Error is:
```
22.48 go: downloading github.com/bits-and-blooms/bitset v1.14.3
69.57 # github.com/dunglas/frankenphp/caddy/frankenphp
69.57 /usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
69.57 /usr/bin/ld: cannot find -lwatcher
69.57 collect2: error: ld returned 1 exit status
69.57 
```

**Reply by dunglas** [reply]
Can you change `go build -tags=nobadger,nomysql,nopgx` by `go build -tags=nowatcher,nobrotli,nobadger,nomysql,nopgx`?

The watcher and Brotli features require extra c libraries to install manually.

This is something we are polishing.

**Reply by withinboredom** [reply]
I'd also recommend a few more configure options:

```
./configure --with-bz2 --enable-ctype --with-curl --enable-filter --enable-mbstring --enable-pcntl --enable-phar --enable-posix --with-readline --enable-sockets --with-sodium --with-zlib --enable-intl --with-openssl --with-zip --with-pear --enable-gd --with-avif --with-webp --with-jpeg --with-xpm --with-gmp --enable-embed --enable-cli --enable-phar --with-mysqli --enable-opcache
```

replacing mysqli with whatever database you need (such as pdo and friends), along with removing/adding other features you want php to support. You can also dump `./configure --help` for a full list. Keep in mind that `--enable-*` means no dependencies are needed, but `--with-*` means dependencies are needed. So `--with-mysqli` requires the headers for mysql installed and `--with-curl` needs the curl dev library installed. Some of those are supposed to be enabled by default, but my team tends to be explicit if we are using those features.

**Reply by geoidesic** [reply]
Ok thanks for all the feedback. Between that and ChatGPT's help, I got quite a bit further. Here's the Dockerfile I've ended up with:
```Dockerfile
# Base image for AlmaLinux 9 on AArch64
FROM almalinux:9 AS common
# Install EPEL and CBR repositories
RUN dnf -y update && \
    dnf clean all

RUN dnf install -y epel-release \
    && dnf config-manager --set-enabled crb \
    && dnf clean all

# Install dependencies
RUN dnf -y update && \
    dnf install -y \
    gcc \
    gcc-c++ \
    make \
    brotli-devel \
    tar \
    libticonv \
    bison \
    re2c \
    pkgconfig \
    openssl-devel \
    libxml2-devel \
    sqlite-devel \
    oniguruma-devel \
    libpng-devel \
    libjpeg-devel \
    libzip-devel \
    mlocate \
    bzip2-devel \
    libcurl-devel \
    libavif-devel \
    libwebp-devel \
    libXpm-devel \
    gmp-devel \
    libicu-devel \
    readline-devel \
    libsodium-devel \
    git 


    
# Download and install Go manually
WORKDIR /usr/src
RUN curl -LO https://go.dev/dl/go1.22.0.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.22.0.linux-amd64.tar.gz && \
    rm go1.22.0.linux-amd64.tar.gz

# Add Go to PATH
ENV PATH="/usr/local/go/bin:${PATH}"

# Download and extract PHP source
WORKDIR /usr/src/php
RUN curl -L https://www.php.net/distributions/php-8.2.11.tar.gz | tar xz --strip-components=1

# Configure PHP for FrankenPHP build
RUN ./configure \
    --enable-embed \
    --enable-zts \
    --disable-zend-signals \
    --enable-zend-max-execution-timers \
    --with-bz2 --enable-ctype --with-png --with-curl --enable-filter --enable-mbstring --enable-pcntl --enable-phar --enable-posix --with-readline --enable-sockets --with-sodium --with-zlib --enable-intl --with-openssl --with-zip --with-pear --enable-gd --with-avif --with-webp --with-jpeg --with-xpm --with-gmp --enable-embed --enable-cli --enable-phar --with-mysqli --with-pdo_mysql --enable-opcache  && \
    make -j"$(nproc)" && \
    make install

    
# Set environment variables for cross-compiling on ARM64
ENV GOARCH=arm64 \
CGO_ENABLED=1

# Download and compile FrankenPHP with adjusted flags for ARM64
WORKDIR /usr/src
# Build FrankenPHP binary
RUN curl -L https://github.com/dunglas/frankenphp/archive/refs/heads/main.tar.gz | tar xz && \
    cd frankenphp-main/caddy/frankenphp && \
    CGO_CFLAGS="$(php-config --includes)" \
    CGO_LDFLAGS="$(php-config --ldflags | sed 's/-m64//') $(php-config --libs)" \
    go build -tags=nowatcher,nobrotli,nobadger,nomysql,nopgx

# Using xcaddy for additional modules (uncomment and modify to include extra Caddy modules)
# RUN curl -fsSL https://github.com/caddyserver/xcaddy/releases/latest/download/xcaddy_linux_arm64 -o /usr/local/bin/xcaddy && \
#     chmod +x /usr/local/bin/xcaddy && \
#     XCADDY_GO_BUILD_FLAGS="-ldflags='-w -s -extldflags \'-Wl,-z,stack-size=0x80000\'" xcaddy build \
#         --output /usr/local/bin/frankenphp \
#         --with github.com/dunglas/frankenphp/caddy \
#         --with github.com/dunglas/mercure/caddy \
#         --with github.com/dunglas/vulcain/caddy


# Final stage to copy the binary to a clean image
FROM almalinux:9
ENV LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}"

# Copy compiled PHP and FrankenPHP binary from builder stage
COPY --from=common /usr/local/bin/php /usr/local/bin/php
COPY --from=common /usr/src/frankenphp-main/caddy/frankenphp/frankenphp /usr/local/bin/frankenphp
COPY --from=common /usr/lib64/ /usr/lib64/
COPY --from=common /usr/local/lib/libphp.so /usr/local/lib/



# Set worker mode to keep container active
ENV FRANKENPHP_CONFIG="worker /app/index.php"

# Expose necessary ports
EXPOSE 80 443

# Default command
CMD ["/usr/local/bin/frankenphp"]
```

However, it doesn't stay up. I'm launching it via `docker compose` with this yml:
```yml
  frankenphp:
    build:
      context: .
      dockerfile: php/caddy/frankenphp/Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - ./app:/app
    extra_hosts:
      host.docker.internal: host-gateway
  ```
  
  The logs:
  ```
  frankenphp-1 exited with code 0 
  ```
  
  I also tried mapping the Caddyfile
  ```
    frankenphp:
    build:
      context: .
      dockerfile: php/caddy/frankenphp/Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - ./app:/app
      - ./php/caddy/frankenphp/Caddyfile:/etc/frankenphp/Caddyfile 
    extra_hosts:
      host.docker.internal: host-gateway
  ```
  
  But that didn't make any difference.
