### DISCUSSION TITLE
Having trouble running Laravel with docker + frankenphp

### DISCUSSION THREAD

**Discussion by Marchiuzzz** [php/frankenphp#1138] [Q&A]
I want to host my Laravel application using Docker and frankenphp but without using Octane. It seems like an easy task following the docs but I have one more requirement - the container must run on host network, therefore, it should be running on some custom port as port 80 is already taken, I also don't need any ssl management because that's already done by a reverse nginx proxy on the production server. 

Here's my dockerfile
```
FROM dunglas/frankenphp
 
ENV SERVER_NAME=localhost:8085
RUN apt-get update && apt-get install -y libz-dev libmemcached-dev libssl-dev && rm -r /var/lib/apt/lists/*

RUN set -eux \
    && pecl install memcached \
    && docker-php-ext-enable memcached \
    && true

RUN docker-php-ext-install mysqli pdo pdo_mysql

RUN install-php-extensions \
    pcntl
```
My docker-compose file
```
version: "3"
services:
  usersite-frankenphp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - memcached
    network_mode: "host"
  memcached:
    image: "memcached:alpine"
    ports:
      - "11211:11212"
volumes:
  caddy_data:
  caddy_config:
```
And the Caddyfile
```
{
	# Enable FrankenPHP
	frankenphp
}

:8085 {
    root * /public
    encode zstd br gzip
    php_server
}
```

I hoped my project would be served on port 8085 with this setup but it's not.
![image](https://github.com/user-attachments/assets/94213737-f52a-4837-ad58-62bbbd2403af)

I guess I'm just missing something really simple, yet crucial. Any help would be much appreciated.
