### DISCUSSION TITLE
docker yml file does not automatically install all extensions

### DISCUSSION THREAD

**Discussion by abda11ah** [php/frankenphp#1223] [General]
I don't know if it's a bug or not.
In PHPinfo, only the pdo_mysql extension is installed (I use Dockge):

here's my file :

```
version: "3.8"
services:
  php:
    image: dunglas/frankenphp
    build:
      context: .
      dockerfile_inline: |
        FROM dunglas/frankenphp
        RUN install-php-extensions \
        gd pdo_mysql intl opcache xdebug
    restart: always
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - /var/www:/app # Mount your application directory
      - /var/www/phpconf:/usr/local/etc/php/conf.d # Custom PHP configuration directory
      - caddy_data:/data
      - caddy_config:/config
    #  environment: null - FRANKENPHP_CONFIG=worker /app/public/index.php  # Specify your worker script
    tty: true
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password # Set your desired root password here
      MYSQL_DATABASE: db # Optional: create a database on startup
      MYSQL_USER: user # Optional: create a user (uncomment and set)
      MYSQL_PASSWORD: user_password # Optional: password for the created user (uncomment and set)
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  caddy_data: null
  caddy_config: null
  mariadb_data: null
networks: {}

```
