### DISCUSSION TITLE
How to access Laravel Octane on default ports with Frankenphp and Docker

### DISCUSSION THREAD

**Discussion by malyutki** [php/frankenphp#1258] [Q&A]
I'm struggling with how to set up docker-compose (or dockerfile) to work with Laravel Octane by default.

I'm using basic things from https://frankenphp.dev/docs/docker/.

I also changed Caddyfile to revert_proxy port 8000.

When I'm executing command inside container everything works great, but when I tried supervisor or ENTRYPOINT in Dockerfile it wasn't working. In both cases I know that the octane was running, but it's not working.

I also tried adding ENV FRANKENPHP_CONFIG with frankenphp-worker.php but it didn't change a bit. Booting application just as normal

**Comment by AlliBalliBaba** [comment]
What does your docker-compose.yml look like? Are you on Mac/WSL/Linux? You don't necessarily need a reverse proxy with FrankenPHP, you can just do something like this and then map the port 8000:

```
:8000 {
	route {
		root /app/public
		encode zstd br gzip
		php_server {
			index frankenphp-worker.php
		}
	}
}
```

**Comment by malyutki** [comment]
I'm on Mac and did something else. I changed index.php, because I see that native worker works only when has index.php name.

```
services:
    php:
        build: ./server
        # uncomment the following line if you want to run this in a production environment
        restart: always
        ports:
            - "80:80" # HTTP
            - "443:443" # HTTPS
            - "443:443/udp" # HTTP/3
            - "8000:8000"
        volumes:
            - ../:/app
            - caddy_data:/data
            - caddy_config:/config
            - ./server/caddy:/etc/caddy
        environment:
            - FRANKENPHP_CONFIG=worker /app/public/index.php
        # comment the following line in production, it allows to have nice human-readable logs in dev
        tty: true
        networks:
            - backend
```


index.php
```
<?php

if ((! ($_SERVER['FRANKENPHP_WORKER'] ?? false)) || ! function_exists('frankenphp_handle_request')) {
    require_once __DIR__ . '/index2.php';
} else {
// Set a default for the application base path and public path if they are missing...
    $_SERVER['APP_BASE_PATH'] = $_ENV['APP_BASE_PATH'] ?? $_SERVER['APP_BASE_PATH'] ?? __DIR__ . '/..';
    $_SERVER['APP_PUBLIC_PATH'] = $_ENV['APP_PUBLIC_PATH'] ?? $_SERVER['APP_BASE_PATH'] ?? __DIR__;

    require __DIR__ . '/../vendor/laravel/octane/bin/frankenphp-worker.php';
}
```

Now it works and I hope that this native worker will work at least as good as it would with Octane
