### DISCUSSION TITLE
Releasing the PHP executable/worker in CLI context

### DISCUSSION THREAD

**Discussion by Guikingone** [php/frankenphp#1357] [Q&A]
Hi 👋🏻 

Small question regarding the usage of the worker in CLI context, it seems that when enabling the worker mode (in `compose.yml` file or via env variable) and using the CLI (think `cache:clear`, `doctrine:database:drop`, etc) in a Symfony project, the binaries does not release existing processes and/or tend to create a lot of them each time, is there any workaround to disable the worker in CLI context or maybe force it to only use one worker for this type of use case?

I'm asking because is kind of sad to not being able to delete a database because Doctrine tells us that a process is already connected to it 😄

For information, i'm using the worker var this way (`compose.override.yml`): 

```yaml
services:
    foo:        
        build:
            context: .cloud/docker/php
                target: dev
        working_dir: /srv/app
        volumes:
              - ./:/srv/app
        environment:
              FRANKENPHP_CONFIG: 'worker /srv/app/public/index.php'
```

Thanks again for the help and have a great day 🙂
