### DISCUSSION TITLE
FrankenPHP watch mode doesn't detect file changes with Docker (Ubuntu)

### DISCUSSION THREAD

**Discussion by sdkOyh2726** [php/frankenphp#1419] [General]
I'm using FrankenPHP with Docker Compose on native Ubuntu (not Docker Desktop) for a Symfony application. Even though I've enabled "watch" mode, FrankenPHP isn't detecting any PHP file changes, and thus does not automatically reload the application. I must manually restart the container every time.

### Configuration:

**Dockerfile:**

```
FROM dunglas/frankenphp:sha-30e33e0-php8.2

ENV FRANKENPHP_CONFIG="worker ./public/index.php --watch"

# add additional extensions here:
RUN install-php-extensions \
    pdo_mysql \
    gd \
    intl \
    zip \
    opcache
```

**Docker-compose.yml:**
```

version: '3'

services:
  frankenphp:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      APP_RUNTIME: "Runtime\\FrankenPhpSymfony\\Runtime"

    volumes:
      - $PWD:/app

    ports:
      - "8001:80"
      - "8000:443"
      - "443:443/udp"

    tty: true
```

**OS: Native Ubuntu**

**Expected behavior:**

FrankenPHP should automatically reload when PHP files change, without needing a manual container restart.

**Actual behavior:**

No reload occurs without manually restarting the container.

**Questions:**

What's the recommended approach for further diagnosing or permanently resolving this issue?

Thanks for your help!
