### DISCUSSION TITLE
can I use frankenphp to replace a php-fpm container?

### DISCUSSION THREAD

**Discussion by danhimalplanet** [php/frankenphp#376] [Ideas]
I have an ubuntu baremetal host.  I run caddy on it.  I built the caddy binary with xcaddy

I have a php-fpm docker container, I run like so:
```
services:
    php:
        image: php:8.3.0-fpm-alpine
        volumes:
          - /srv/sites/my-site.com:/var/www/html
        ports:
          - 9000:9000
```
my caddy config block:
```
        @my-site host my-site.com
        handle @my-site {
                root * /srv/sites/my-site.com
                php_fastcgi localhost:9000 {
                        root /var/www/html
                }
                file_server
        }
```

I brought up a frankenphp container:
```
docker run -d --name frankenphp -v /srv/sites/my-site.com:/app/public \
    -p 9001:80 \
    dunglas/frankenphp
```

I tried a different block in caddy config:
```
	@my-site host my-site.com
	handle @my-site {
		root * /srv/sites/my-site.com
                php_fastcgi localhost:9001 {
			root /app/public
	        }	
		file_server
	}
```

Servers static html just fine.    Can't process php files.

Is it possible to do this?
