### DISCUSSION TITLE
How to reverse proxy frankenphp

### DISCUSSION THREAD

**Discussion by Asociateone** [php/frankenphp#718] [Q&A] [answered]
I have both my development and production environments running on a single Digital Ocean droplet, using a Frankenphp image. To ensure the correct application is served, I've implemented Caddy.

Since Caddy handled SSL certificate creation, I disabled it within the Frankenphp image by setting SERVER_NAME: :80 in the compose.yaml file. When I visited example.com, it correctly displayed the Laravel default page, which was a good sign.

However, when I attempted to log in, the styling failed to load because the CSS and JavaScript files were being served over HTTP internally. Browsers like Google Chrome don't allow this behavior.

I attempted to resolve this issue by adding a global directive to the Caddyfile of my Caddy image, as suggested in the documentation. Unfortunately, this didn't work as expected. I also consulted the [Caddy config documentation](https://frankenphp.dev/docs/config/#caddyfile-config), but either my implementation was incorrect, or I misunderstood the instructions.

Does anyone have an idea on how to resolve this issue?

**Comment by withinboredom** [comment]
CSS and JS urls is not a caddy issue, but something with your configuration and/or app code

**Reply by Asociateone** [reply]
I believe it is.

The initial call arrives in Caddy, which then directs it toward the correct FrankenPHP image. However, this image operates on HTTP instead of HTTPS. Turning on HTTPS with FrankenPHP seems to disrupt their ability to communicate with each other (or so it appears). As I'm quite new to this, any thoughts or insights would be greatly appreciated. 😊

**Reply by withinboredom** [reply, marked as answer]
Heh. It isn't. I could probably write a book about the problem you are stuck on, and we have all been stuck on some version of this problem. I don't want to spoil it for you because it's a good learning experience for how the web works... but I will give you a direction.

I recommend reading up on https://laravel.com/docs/11.x/urls and note:

> The generated URL will automatically use the scheme (HTTP or HTTPS) and host from the current request being handled

So you need to figure out one of two options:

1. How to keep the original https request to your application visible to your application. (Not sure how to do this with caddy tbh)
2. Manually set the application url in your env and do not rely on the request (this is more secure but depending on your application, may not be realistic).

**Reply by Asociateone** [reply]
Thank you :)

**Reply by larsverp** [reply]
Curious to know if you managed to keep the original https request to your application visible to your application in Caddy? Since I'm also going through some struggling with this issue 🧐

**Reply by Asociateone** [reply]
I'm still not a hero in this so, I will just post below what I did:

## Your `compose.yaml` for your Caddy Reverse proxy container

```yaml
networks:
  caddy:
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80 
      - 443:443
    volumes:
      - /home/name/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/name/caddy/site:/srv
      - /home/name/caddy/caddy_data:/data
      - /home/name/caddy/caddy_config:/config
    networks:
      - caddy
volumes:
  caddy_data:
    external: true
  caddy_config:
```



## Your CaddyFile for your Caddy reverse proxy container
```
yoururl.com {
    reverse_proxy yourfrankenphpcontainername:80 // Or 8000 if you use Octane
}
dev.yoururl.com {
    reverse_proxy devyourfrankenphpcontainername:80 // Or 8000 if you use Octane
}
```

## Your `compose.yaml for running frankenphp`

Ensure that you do not serve your FrankenPHP container over HTTPS, if you do the application will throw a 500 error.

```yaml
services:
  frankenphp:
    container_name: yourfrankenphpcontainername
    restart: always
    build:
      context: .
    entrypoint: php artisan octane:frankenphp --max-requests=1 # remove this line if you do not use octane
    networks:
      - caddy_network # this is the network from the Caddy reverse proxy network
    volumes:
      - .:/app
    environment:
      SERVER_NAME: :80 # make sure it does not serve over HTTPS because the reverse proxy already fixes this for you
volumes:
  caddy_data:
  caddy_config:
networks:
  caddy_caddy:
    external: true
```
> I don't need to specify internal ports for Caddy to communicate with the container, it automatically uses the container's internal ports (either 80 or 8000 for Octane).

## Your Laravel application

To ensure that your application runs over HTTPS, add this to your `AppServiceProvider.php`:

```php
public function boot(): void
{
    URL::forceScheme('https');
}
```

**Reply by dunglas** [reply]
Another (cleaner) option would be to use trusted headers:

1. Set the IP of the reverse proxy to trust using the [`trusted_proxies` directive](https://caddyserver.com/docs/caddyfile/options#trusted-proxies) in the FrankenPHP `Caddyfile`
2. Add the IP of the reverse proxy in your Laravel or Symfony config (Laravel is using Symfony under the hood for this), and mark `X-Forwarded-Proto`, `X-Forwarded-For` and `X-Forwarded-Host` (they are set by default by Caddy) as trusted headers: [Laravel docs](https://laravel.com/docs/11.x/requests#configuring-trusted-proxies) / [Symfony docs](https://symfony.com/doc/current/deployment/proxies.html)

Alternatively, Caddy supports the [Proxy Protocol](https://github.com/haproxy/haproxy/blob/master/doc/proxy-protocol.txt). To enable this feature:

1. Enable the proxy protocol at the reverse proxy level using [the `proxy_protocol` option of the `http` transport](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#proxy_protocol)
2. Enable [the `proxy_protocol` listener wrapper](https://caddyserver.com/docs/json/apps/http/servers/listener_wrappers/proxy_protocol/) in FrankenPHP

Using the proxy protocol is less popular but has the advantage of not requiring to configure the PHP app itself.

Both options have the advantage of also preserving the original Host and IP in addition to the scheme.

**Reply by Asociateone** [reply]
I will let you know when i got it working. Thanks for the Feedback :)

**Reply by larsverp** [reply]
@dunglas I can't seem to get this working. I run my Symfony application behind an CF -> HaProxy. The CF server is setup to handle the ssl for me. The application is fully accesible over https, however all the calls the application makes to itself (For example when getting the debugbar) are over http for some reasone.

My dockerfile is defined like this:
```dockerfile
FROM dunglas/frankenphp:latest-php8.3-bookworm

ENV SERVER_NAME=:80

# Enable PHP production settings
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# Copy app files
COPY . /app

COPY Caddyfile /etc/caddy/Caddyfiles

...
```

This is the Caddyfile I copy:

```Caddyfile
{
    {$CADDY_GLOBAL_OPTIONS}

    frankenphp {
            {$FRANKENPHP_CONFIG}
    }

    # https://caddyserver.com/docs/caddyfile/directives#sorting-algorithm
    order mercure after encode
    order vulcain after reverse_proxy
    order php_server before file_server
    order php before file_server
}

{$CADDY_EXTRA_CONFIG}

{$SERVER_NAME:localhost} {
    root * public/
    encode zstd br gzip

    trusted_proxies static private_ranges CF-IP-1 CF-IP-2

    {$CADDY_SERVER_EXTRA_DIRECTIVES}

    php_server
}
```

All my internal routing uses the 10.0.0.0 network so that should be working as expected.

Any idea what I'm doing wrong? 🧐

**Reply by bohdan-shulha** [reply]
Have you added trusted proxies directive to symfony itself?

Similar to how it's done in Laravel: https://laravel.com/docs/11.x/requests#configuring-trusted-proxies

**Reply by larsverp** [reply]
@bohdan-shulha Yep! It all worked fine before I introduced the FrankenPHP layer.

**Reply by bohdan-shulha** [reply]
Try to apply as a global configuration.

```
{
    servers {
        trusted_proxies static private_ranges ...
    }

    {$CADDY_GLOBAL_OPTIONS}

    frankenphp {
            {$FRANKENPHP_CONFIG}
    }

    ...... other settings
}
```

it works fine for me (with Laravel). The only thing - I had to manually add these lines, as CADDY_GLOBAL_OPTIONS resulted in some syntax errors. 🤷‍♂️

**Reply by SayHeyD** [reply]
I am also having issues with proxying frankenphp. (Laravel 11)

`bootstrap/app.php`:

```php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;
use Illuminate\Http\Request;

return Application::configure(basePath: dirname(__DIR__))
    ...
    ->withMiddleware(function (Middleware $middleware) {
        $middleware->trustProxies(
            at: [
                '*',
            ],
            headers:    Request::HEADER_FORWARDED |
                        Request::HEADER_X_FORWARDED_FOR |
                        Request::HEADER_X_FORWARDED_HOST |
                        Request::HEADER_X_FORWARDED_PORT |
                        Request::HEADER_X_FORWARDED_PROTO |
                        Request::HEADER_X_FORWARDED_PREFIX
        );
    })
    ...
    ->create();
```

Dockerfile:

```dockerfile
FROM dunglas/frankenphp:1.1-builder-php8.2.16

# Set Caddy server name to "http://" to serve on 80 and not 443
# Read more: https://frankenphp.dev/docs/config/#environment-variables
ENV SERVER_NAME="http://"

RUN curl -fsSL https://deb.nodesource.com/setup_20.x -o nodesource_setup.sh && \
    bash nodesource_setup.sh

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    curl \
    git \
    unzip \
    librabbitmq-dev \
    libpq-dev \
    supervisor \
    nodejs

RUN install-php-extensions \
    gd \
    pcntl \
    opcache \
    pdo \
    pdo_pgsql \
    pdo_mysql \
    redis \
    intl \
    zip

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Copy the Laravel application files into the container.
COPY .. .

# Start with base PHP config, then add extensions.
COPY ./.docker/php.ini /usr/local/etc/php/

# Copy supervisor config files into correct location on the server
COPY ./.docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./.docker/supervisord.dev.conf /etc/supervisor/conf.d/supervisord.dev.conf
COPY ./.docker/laravel.Caddyfile /etc/caddy/Caddyfile

# Ensure entrypoint script can be executed
RUN chmod +x ./.docker/docker-entrypoint.sh

# Ensure docker-compose-wait can be executed
RUN chmod +x ./.docker/wait

# Install PHP extensions
RUN pecl install xdebug

# Install Laravel dependencies using Composer.
RUN composer install --no-dev

# Install node dependencies and build frontend
RUN npm install --no-dev && \
    npm run build

# Enable PHP extensions
# RUN docker-php-ext-enable xdebug

# Set permissions for Laravel.
RUN chown -R www-data:www-data storage bootstrap/cache

EXPOSE 80 443

# Start Supervisor.
CMD ["./.docker/docker-entrypoint.sh"]
```

Caddyfile:

```caddy
{
	{$CADDY_GLOBAL_OPTIONS}

	servers {
		trusted_proxies static 0.0.0.0/0
	}

	frankenphp {
		#worker /path/to/your/worker.php
		{$FRANKENPHP_CONFIG}
	}

	# https://caddyserver.com/docs/caddyfile/directives#sorting-algorithm
	order mercure after encode
	order vulcain after reverse_proxy
	order php_server before file_server
	order php before file_server
}

{$CADDY_EXTRA_CONFIG}

{$SERVER_NAME:localhost} {
	#log {
	#	# Redact the authorization query parameter that can be set by Mercure
	#	format filter {
	#		wrap console
	#		fields {
	#			uri query {
	#				replace authorization REDACTED
	#			}
	#		}
	#	}
	#}

	root * public/
	encode zstd br gzip

	# Uncomment the following lines to enable Mercure and Vulcain modules
	#mercure {
	#	# Transport to use (default to Bolt)
	#	transport_url {$MERCURE_TRANSPORT_URL:bolt:///data/mercure.db}
	#	# Publisher JWT key
	#	publisher_jwt {env.MERCURE_PUBLISHER_JWT_KEY} {env.MERCURE_PUBLISHER_JWT_ALG}
	#	# Subscriber JWT key
	#	subscriber_jwt {env.MERCURE_SUBSCRIBER_JWT_KEY} {env.MERCURE_SUBSCRIBER_JWT_ALG}
	#	# Allow anonymous subscribers (double-check that it's what you want)
	#	anonymous
	#	# Enable the subscription API (double-check that it's what you want)
	#	subscriptions
	#	# Extra directives
	#	{$MERCURE_EXTRA_DIRECTIVES}
	#}
	#vulcain

	{$CADDY_SERVER_EXTRA_DIRECTIVES}

	php_server
}
```

nginx config:

```nginx
location ~ /(dashboard|sanctum|filament|livewire) {
      # Pass to laravel
      proxy_pass http://127.0.0.1:3006;
      proxy_set_header Host $http_host;
      proxy_set_header Scheme $scheme;
      proxy_set_header X-Forwarded-Proto $scheme; 
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      # proxy_set_header X-Forwarded-Host $http_host;
      # proxy_set_header X-Forwarded-Port 443;
      # proxy_set_header Upgrade $http_upgrade;
      allow all;
 24 }
```

`.env`:

```env
...
APP_URL=https://example.com/
...
```

Everything works, except for Laravel generating URLs with `http://` as the specified protocol and not `https://`. This wouldn't be a problem except for the logout, where I get the message "sending this form may not be secure".

If anyone has a working example of a setup like this, it would be great.

**Comment by 7system7** [comment]
I have the same problem. It seems it is an impossible mission... so frustrating. I spent long hours to handle this problem this. (3rd time... it is around net 19 hours) And **ZERO** success. 😆 It seems, my 15+ years of experience is not enough to set up a single Symfony-MariaDB-FrankenPHP config **under reverse proxy**. So sad. Although, this is just further proof that I am more of a developer than a devops.

The FrankenPHP seems a very good project and idea but under reverse proxy it is real impossible to configure. I maintain 12 projects but I can run only 2 of them w/ FPHP, because they can be reached through the VPS and wired directly to the FrankenPHP container. All others should be run under reverse proxy.

Anyway, I would share my config, if a miracle happens, and there is a genius who can find my failure through them. **Please** do not hesitate to educate me. I would like to share the most relevant parts. 
Meanwhile, I use a native Caddy-PHP-FPM solution instead this. Its configuration can takes 2 or maximum 5 minutes. 😢 

***

**Rant is over.**

This is an old (old but not legacy, React v19, PHP 8.4.* and Symfony 7.2.*) project, and I have a CI/CD script (Gitea Actions) for releasing it. I would be soooo good to use under FrankenPHP. (And the other 12 projects)

My FrankenPHP's `Caddyfile`

```
{
	frankenphp
	email "<email-address>"
	servers {
		trusted_proxies static 0.0.0.0/0
	}
}

http://{$APP_DOMAIN} {
	root * /app/public
	encode zstd br gzip
	php_server
	vulcain

	route /.well-known/mercure {
            ...<mercure-config>
	}
}
```

My Symfony's .env file

```envvar
###> symfony/framework-bundle ###
APP_ENV=dev
APP_SECRET=<secret>
APP_VERSION=2024.4.0
APP_DOMAIN=127.0.0.1
APP_NAME=natur-api
TRUSTED_PROXIES=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
###< symfony/framework-bundle ###

###> doctrine/doctrine-bundle ###
DATABASE_HOST=127.0.0.1                          <--- Yeah, I know, this should be the docker container's name, (db) but that does not work too.
DATABASE_DB=natur-api
DATABASE_USER=natur-user
DATABASE_PASSWORD=<pass>
DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:7306/${DATABASE_DB}?serverVersion=11.7.2-MariaDB
###< doctrine/doctrine-bundle ###
```

Projects `Dockerfile`

```Dockerfile
FROM dunglas/frankenphp:1

COPY . /app
COPY --link bin/docker/Caddyfile /etc/caddy/Caddyfile

RUN cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini
RUN cp bin/docker/php.ini-production $PHP_INI_DIR/conf.d/custom-php.ini
RUN install-php-extensions \
	@composer \
	pdo_mysql \
	gd \
	mbstring \
	bcmath \
	intl \
	zip \
	opcache \
	apcu \
	iconv

ENV COMPOSER_ALLOW_SUPERUSER=1
ENV APP_RUNTIME=Runtime\\FrankenPhpSymfony\\Runtime
ENV FRANKENPHP_CONFIG="worker ./public/index.php"
```

The Docker's compose.yaml

```yaml
services:
  db:
    # @see https://hub.docker.com/_/mariadb
    image: mariadb:11.7.2
    restart: always
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    container_name: '${APP_NAME}-db'
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD:-!ChangeMe!}
      - MARIADB_DATABASE=${DATABASE_DB:-app}
      - MARIADB_USER=${DATABASE_USER:-app}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD:-!ChangeMe!}
    ports:
      - "7306:3306"
    volumes:
      - database:/var/lib/mysql:rw
    networks:
      - natur_api_network
  api:
    # @see https://source.splendidbear.org/NaturAgro/api
    # @see https://hub.docker.com/r/dunglas/frankenphp
    image: dunglas/frankenphp:1-alpine
    build: .
    restart: always
    container_name: '${APP_NAME}-app'
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
      - MERCURE_PUBLISHER_JWT_KEY={$MERCURE_PUBLISHER_JWT_KEY}
      - MERCURE_SUBSCRIBER_JWT_KEY={$MERCURE_SUBSCRIBER_JWT_KEY}
    ports:
      - "7080:80"
      - "7443:443"
      - "7443:443/udp"
    volumes:
      - ./:/app
      - /var/storage/storage:/app/public/storage
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      db:
        condition: service_healthy
    networks:
      - natur_api_network
volumes:
  caddy_data:
  caddy_config:
  database:
networks:
  natur_api_network:
```

This is the host's `Caddyfile`. Yes, it is just developer environment. The commented sections have been worked as expected for 10 years.
And yes, I have the `/etc/hosts` config w/  `127.0.0.1 natur-exp.local`

```
natur-exp.local {
	# route {
	# 	root * /var/www/natur-api/public
        #
	#         encode zstd gzip
	#         php_fastcgi unix//run/php-fpm/php-fpm.sock
	#         file_server
	# }

	reverse_proxy localhost:7080

	log {
	       output file /var/log/caddy/natur-api.access.log {
		        roll_size 3MiB
	                roll_keep 5
	                roll_keep_for 48h
	       }
	       format console
	}
}
```
