### DISCUSSION TITLE
Chrome "Connection Reset"

### DISCUSSION THREAD

**Discussion by fpolli** [php/frankenphp#724] [Q&A]
I have a FrankenPHP-Laravel Octane set up in a docker container that I am trying to test at localhost. A couple of requests made it to Octane and responses were served. Then I tried to click a link on my test welcome page that wet to another page and got "Connection Reset" from Chrome. I entered the url of the second page into the address bar, and it was served. The Octane log reflects these successful requests. However, since that last success, every attempt to browser to localhost produces the same "Connection Reset" error from Chrome and nothing shows up on the Octane log. I'm guessing the request is not even getting to Caddy. I have tried restarting the docker container and clearing the data in Chrome.

Chrome also gives me the "your connection to this site is not secure" warning.

In case the info is helpful:

Dockerfile
```

FROM dunglas/frankenphp

RUN install-php-extensions pcntl

RUN apt-get update && apt-get install -y libmemcached-dev libssl-dev zlib1g-dev \
  && pecl install memcached-3.2.0 \
  && docker-php-ext-enable memcached

COPY . /app

RUN curl -sS https://getcomposer.org/installer -o composer-setup.php

RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer

RUN curl -fsSL https://deb.nodesource.com/setup_current.x | bash - && \
  apt-get install -y nodejs \
  build-essential && \
  node --version && \ 
  npm --version

RUN apt-get install -y ffmpeg

ENTRYPOINT ["php", "artisan", "octane:frankenphp"]
```
Docker compose
```

Name: name

services:
  app:
    build:
      context: .
    entrypoint: php artisan octane:frankenphp
    ports:
      - "80:8000"
      - "443:443"
      - "443:443/udp" # HTTP/3
    depends_on:
      - db
      - cache
    volumes:
      - storage://D/www/laravel-projects/storage
      - ../:/app
      - caddy_data:/data
      - caddy_config:/config
    #command: sleep infinity,
    networks:
      - storefront
      - backroom
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - data://D/PostgreSQL/data
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
    networks:
      - backroom
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: email
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - backroom
    depends_on:
      - db

  cache:
    image: memcached:latest
    restart: unless-stopped
    #volumes:
    networks:
      - backroom

networks:
  storefront:
  backroom:

volumes:
  data:
  storage:
  caddy_data:
  caddy_config:
  pgadmin_data:
```
Laravel .env values of relevance:

APP_URL=https://localhost
OCTANE_SERVER=frankenphp
OCTANE_HTTPS=true

I changed nothing on octane.php config.

Octane status check shows Octane is running.
