### DISCUSSION TITLE
[QUESTION] deploying to production

### DISCUSSION THREAD

**Discussion by ezekel** [php/frankenphp#747] [General]
Hi 

When deploying to production should we need to use Caddyfile or is this enough to deploy?

```
FROM dunglas/frankenphp:latest

ENV SERVER_NAME=mysite.com//just example

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

RUN apt-get update && apt-get install -y \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# Add additional PHP extensions here:
RUN install-php-extensions \
    pdo_mysql \
    gd \
    intl \
    zip \
    opcache

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY . /app

```

Thank you in advance

**Comment by withinboredom** [comment]
You can add `@composer` to your `install-php-extensions` list and have it install it. It also checks the SHA (IIRC) to ensure you have a non-corrupted composer installed.

Looks about right to me! Here's a real Dockerfile for a production service if you want to compare notes:

```dockerfile
FROM dunglas/frankenphp:1-php8.3-bookworm AS builder

ARG EXTRA_EXTENSIONS="opcache"
RUN install-php-extensions @composer intl ctype mbstring apcu pdo pdo_pgsql zip $EXTRA_EXTENSIONS
RUN apt-get update && apt-get install -y inotify-tools && \
    rm -rf /var/lib/apt/lists/*

RUN cp "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"; \
    sed -i 's/variables_order = "GPCS"/variables_order = "EGPCS"/' "$PHP_INI_DIR/php.ini";

ENV SERVER_NAME=":8080" FRANKENPHP_CONFIG='worker /app/public/index.php'

RUN useradd -r -d /app -s /bin/bash -g root -G sudo -u 1000 caddy; \
    mkdir /data; \
    mkdir /config; \
    chown caddy:root -R /data; \
    chown caddy:root -R /config;

FROM builder AS production

COPY composer.json composer.lock /app/

RUN composer install --no-dev --optimize-autoloader --apcu-autoloader --no-scripts --no-plugins

COPY src /app/src
COPY public /app/public
COPY bin /app/bin

# run any plugins/scripts as needed
RUN COMPOSER_ALLOW_SUPERUSER=1 composer dump --optimize --apcu --no-dev

RUN echo "xdebug.mode=debug\nxdebug.discover_client_host=1\n" >> $PHP_INI_DIR/php.ini

USER 1000

FROM production AS tests

USER root

COPY . .
RUN composer install || composer install # silly workaround
RUN vendor/bin/pest
```

The `docker-compose.yml` file for development looks something like this:

```yaml
x-service-build: &build
  context: .
  pull: true
  dockerfile: Dockerfile
  target: production
  args:
    EXTRA_EXTENSIONS: "xdebug"

x-service-env: &senv
  DATABASE_USER: root
  DATABASE_PASSWORD: insecure
  DATABASE_HOST: postgres
  DATABASE_PORT: '5432'
  DATABASE_NAME: postgres
  XDEBUG_SESSION: 1
  XDEBUG_CONFIG: "log_level=10"
  # comment out below to enable worker mode and disable xdebug stepping
  FRANKENPHP_CONFIG: ""

services:
  translation-init:
    image: funxtionatics/translation-system
    depends_on:
      postgres:
        condition: service_healthy
    build:
      <<: *build
    environment:
      <<: *senv
    restart: no
    volumes:
      - ./:/app
    command: ['/app/bin/init.sh']
  translation-tests:
    image: funxtionatics/translation-system
    depends_on:
      translation-init:
        condition: service_completed_successfully
    profiles:
      - tests
    build:
      <<: *build
    environment:
      <<: *senv
    volumes:
      - ./:/app
    command: ["vendor/bin/pest"]
  translation-service:
    image: funxtionatics/translation-system
    depends_on:
      translation-init:
        condition: service_completed_successfully
    build:
      <<: *build
    environment:
      <<: *senv
    volumes:
      - ./:/app
    command: ['/app/bin/watch.sh', 'frankenphp run -c /etc/caddy/Caddyfile']
    ports:
      - "8881:8080"
    stop_signal: SIGINT
```

And if you are curious, here's `watch.sh`

```sh
#!/usr/bin/env bash

sigint_handler()
{
  kill -9 $PID
  exit
}

trap sigint_handler SIGINT
trap sigint_handler SIGTERM

while true; do
  # commands to perform any work on changes
  composer dump -o --apcu
  bin/doctrine orm:schema-tool:update --force --complete

  $@ &
  PID=$!
  inotifywait -e modify -e move -e create -e delete -e attrib -r "$(pwd)/src" "$(pwd)/public" "$(pwd)/vendor"
  kill $PID
done
```
