### ISSUE TITLE
Error setting certificate file on latest static binary

### ISSUE THREAD

**Issue by aszenz** [php/frankenphp#1610]
### What happened?

Cannot make http request via symfony http client

> (Symfony\Component\HttpClient\Exception\TransportException(code: 0): Error setting certificate file: /etc/pki/tls/certs/ca-bundle.crt 

As per https://frankenphp.dev/docs/known-issues/#troubleshooting-tlsssl-issues-with-static-binaries, i tried setting these env vars on starting franken php server but the error persists

My env is github actions `ubuntu-latest`

I download the static binary  as:

```     
- name: Install frankenphp binary
  run: curl https://frankenphp.dev/install.sh | sh
```

```
- name: Start frankenphp server
  run: ./frankenphp start --config Caddyfile > e2e/logs/frankenphp.log 2>&1
  env:
   - SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
   - SSL_CERT_DIR: /etc/ssl/certs
```

Caddy file
```
{
  debug
  log {
    output file e2e/logs/caddy.log
    format console
    level DEBUG
  }
  frankenphp
}

:8080 {
  root * public/
  encode gzip
  php_server
}
```

### Build Type

Official static build

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
Using latest static build
```

### Relevant log output

```shell

```
