### ISSUE TITLE
Can't install snuffleupagus php extension

### ISSUE THREAD

**Issue by abda11ah** [php/frankenphp#1635]
### What happened?

it warns about ZTS (thread safe) compatibility and git executable file not found in $PATH

using :

```
services:
  frankenphp:
    build:
      dockerfile_inline: |
        FROM dunglas/frankenphp
        RUN install-php-extensions \
            pdo_mysql \
            gd \
            intl \
            opcache \
            imagick \
            snuffleupagus
        COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
    restart: unless-stopped
    volumes:
      - ${APP_ROOT}:/app
      - ${APP_ROOT}/log:/var/log
      - ${APP_ROOT}/php.ini:/usr/local/etc/php/php.ini
      - ${APP_ROOT}/snuffleupagus.rules:/usr/local/etc/snuffleupagus.rules
      - ${APP_ROOT}/Caddyfile:/etc/frankenphp/Caddyfile
      - ${APP_ROOT}/caddy_data:/data/caddy
      - ${APP_ROOT}/caddy_config:/config/caddy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    networks:
      - default
    env_file:
      - .env
```

```
 ### INSTALLING REMOTE MODULE snuffleupagus ###
138.1 Configuring for:
138.1 PHP Version:             8.4
138.1 PHP Api Version:         20240924
138.1 Zend Module Api No:      20240924
138.1 Zend Extension Api No:   420240924
138.8 checking for grep that handles long lines and -e... /usr/bin/grep
138.8 checking for egrep... /usr/bin/grep -E
138.8 checking for a sed that does not truncate output... /usr/bin/sed
138.8 checking build system type... x86_64-pc-linux-gnu
138.8 checking host system type... x86_64-pc-linux-gnu
138.8 checking target system type... x86_64-pc-linux-gnu
138.8 shtool:echo:Warning: unable to determine terminal sequence for bold mode
138.9 shtool:echo:Warning: unable to determine terminal sequence for bold mode
138.9 checking for gawk... no
138.9 checking for nawk... nawk
138.9 checking if nawk is broken... no
138.9 checking for pkg-config... /usr/bin/pkg-config
138.9 checking pkg-config is at least version 0.9.0... yes
138.9 checking for cc... cc
138.9 checking whether the C compiler works... yes
138.9 checking for C compiler default output file name... a.out
138.9 checking for suffix of executables... 
139.0 checking whether we are cross compiling... no
139.0 checking for suffix of object files... o
139.0 checking whether the compiler supports GNU C... yes
139.0 checking whether cc accepts -g... yes
139.0 checking for cc option to enable C11 features... none needed
139.1 checking how to run the C preprocessor... cc -E
139.1 checking for icc... no
139.2 checking for suncc... no
139.2 checking for system library directory... lib
139.2 checking if compiler supports -Wl,-rpath,... yes
139.2 checking for PHP prefix... /usr/local
139.2 checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
139.2 checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-zts-20240924
139.2 checking for PHP installed headers prefix... /usr/local/include/php
139.2 checking if debugging is enabled... no
139.2 checking if PHP is built with thread safety (ZTS)... yes
139.2 
139.2 Configuring extension
139.2 checking whether to enable snuffleupagus support... yes, shared
139.2 checking whether to enable coverage support... no
139.2 checking whether to enable debug messages... no
139.2 checking whether to enable debug messages... no
139.2 checking for gcc... (cached) cc
139.3 checking whether the compiler supports GNU C... (cached) yes
139.3 checking whether cc accepts -g... (cached) yes
139.3 checking for cc option to enable C11 features... (cached) none needed
139.3 checking whether the C compiler accepts -Wl,-z,relro,-z,now... yes
139.3 checking for NTS... configure: error: ZTS (thread safe) is not supported, please use NTS (standard) build of PHP
------
WARN[0000] current commit information was not captured by the build  error="git was not found in the system: exec: \"git\": executable file not found in $PATH"
failed to solve: process "/bin/sh -c install-php-extensions     pdo_mysql     gd     intl     opcache     imagick     snuffleupagus" did not complete successfully: exit code: 1

```

### Build Type

Docker (Debian Bookworm)

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
not installed
```

### Relevant log output

```shell

```
